config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence:true, length: {maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord

  has_many :microposts, dependent: :destroy
	before_save{self.email=email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name , presence: true , length: {maximum: 50}
	validates :email, presence: true , length: {maximum: 255}, 
	 format: {with: VALID_EMAIL_REGEX },
     uniqueness: {case_sensitive: false }
     has_secure_password
     validates :password , length: {minimum: 6}, presence: true ,allow_nil: true

     # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user=User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		# Log the user in and redirect to the user's show page.
  		log_in user  #method in helper
  		redirect_back_or user  #if user tried to go to page not logged in url will be saved 
      #and redirected to it after default if no was logging 3ady 7yro7 lldefault #redirect_to user(old)
  	else
  		# Create an error message.
  		flash.now[:danger]= 'Inavlid email/password combination'
        render 'new'
  	end
  	
  end

   def destroy
    log_out
    redirect_to root_url
   end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index 
    @users=User.paginate(page: params[:page])
  end

  def show
  	@user=User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])

 
  end

  def new
  	@user=User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      log_in @user #login to create session to save data 
      flash[:success]="welcome to the sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success]="user deleted"
    redirect_to users_url
  end

  private

    def user_params # data from post
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

     # Before filters
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "please log in"
        redirect_to login_url
      end
    end

  # Confirms the correct user.
    def correct_user
      @user=User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
      #root path instead of login path bec user already is login 

    end

   # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin? 
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title= "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			page_title+" | "+base_title
			
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

  # Returns true if the given user is the current user.
 def current_user?(user)
  user==current_user
 end

  # Returns the current logged-in user (if any).
	def current_user
    	@current_user ||= User.find_by(id: session[:user_id])
    end

     # Returns true if the user is logged in, false otherwise.
  	def logged_in?
    	!current_user.nil?
  	end
   
     # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

   # Redirects to stored location (or to the default).
   def redirect_back_or(default)
    redirect_to(session[:forwarding_url]|| default)
    session.delete(:forwarding_url)

   end

   
   # Stores the URL trying to be accessed.
   def store_location
    session[:forwarding_url]=request.original_url if request.get?
   end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user
	def gravatar_for(user, options = { size: 80 })
		gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	    image_tag(gravatar_url ,alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="fooyter">
	<small>	
    	The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    	by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path%></li>
			<li><%= link_to "Contact", contact_path%></li>
			<li><a href="http://news.railstutorial.org/">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
     <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= flash.each do |message_type,message|%>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
      <%end%>

      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>
</html

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div id="alert alert-danger">
			the form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<%= @user.errors.full_messages.each do |msg| %>
			<li><%=msg%></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<%provide(:title,"About")%>

    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title ,'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<%provide(:title,"Help")%>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>
 

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>welcome to sample App</h1>
    <h2>
		This is the home page for the
		<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		sample application.
	</h2>
	<%=link_to "sign up now" , signup_path, class: "btn btn-lg btn-primary"%>
	
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>

  <% if current_user.admin? && !current_user?(user)%>
  	| <%= link_to "delete" , user, method: :delete ,
  	                             data: {confirm: "you sure?"} %>
  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title , "Edit user") %>
<h1> Update your profile </h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		
		<%= f.label :name %>
		<%= f.text_field :name , class: 'form-control'%>

		<%= f.label :email %>
		<%= f.email_field :email , class: 'form-control' %>

		<%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "save changes" , class: 'btn btn-primary' %>
		<% end %>
		
		<div class= "gravatar_edit">
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails" target="_blank">change </a>
			
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
	<%= render @users %>
	<% end -%>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
			  <%= gravatar_for @user %> <!-- call method(exits controller helper) from .rb -->
			  <%= @user.name %>
			</h1>
		</section>
	</aside>
	 <div class="col-md-8">
	    <% if @user.microposts.any? %>
	      <h3>Microposts (<%= @user.microposts.count %>)</h3>
	      <ol class="microposts">
	        <%= render @microposts %>
	      </ol>
	      <%= will_paginate @microposts %>
	    <% end %>
  </div>

</div>